name: Java CI with Maven

on:
  push:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        distribution: 'adopt' # See 'Supported distributions' for available options
        java-version: '11'

    - name: Grant execute permission for mvnw
      run: chmod +x mvnw

    - name: Build with Maven
      run: ./mvnw clean package

    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@master
      with:
        project_id: ${{ secrets.GCP_PROJECT_ID }}
        service_account_key: ${{ secrets.GCP_SA_KEY }}
        export_default_credentials: true

    - name: Deploy cloud function
      run: |
        gcloud functions deploy ${{secrets.GCP_FUNCTION_NAME}} \
        --region=${{secrets.GCP_REGION}} \
        --service-account=${{secrets.GCP_SERVICE_ACCOUNT_ID}}@${{secrets.GCP_PROJECT_ID}}.iam.gserviceaccount.com \
        --entry-point org.springframework.cloud.function.adapter.gcp.GcfJarLauncher \
        --allow-unauthenticated \
        --runtime java11 \
        --trigger-http \
        --source target/deploy \
        --memory 512MB \
        --set-env-vars gitlabToken=${{secrets.GITLAB_TOKEN}},sonarToken=${{secrets.SONAR_TOKEN}},sonarUrl=${{secrets.SONAR_URL}}
